### ISSUE TITLE
There was an error invoking the function - qrcode_svg_1.default is not a constructor

### ISSUE THREAD

**Issue by gmacario** [aquariophilie/axolotl#39]
I managed to install AXOLOTL (main) on a new space under https://solarma.atlassian.net/wiki

However when I try to instantiate the Forge app inside a new Confluence page I got the following error

![image](https://user-images.githubusercontent.com/75182/166213637-c465a115-9bb4-41a4-afe3-9697d8a27aaa.png)

Excerpt from the trace:

```text
Something went wrong
Trace ID: 1184497edbaaf505
There was an error invoking the function - qrcode_svg_1.default is not a constructor

TypeError: qrcode_svg_1.default is not a constructor
    at Object.App [as type] (index.js:30445:18)
    at index.js:2243:36
    at async asyncMap (index.js:2178:24)
    at async index.js:2199:29
    at async asyncMap (index.js:2178:24)
    at async index.js:2261:23
    at async index.js:1711:31
```

**Comment by gmacario** [comment]
Detail of the steps I performed for building and deploying the Forge app:

Logged in as gmacario@hw2228, install Visual Studio Code

* Checkout sources from $GITHUB_REPOSITORY
* Install Node.js 16.x
* Install Forge CLI

```text
gmacario@hw2228:~/github/aquariophilie/axolotl$ forge --version
4.1.1
gmacario@hw2228:~/github/aquariophilie/axolotl$
```

Login to Forge

```text
gmacario@hw2228:~/github/aquariophilie/axolotl$ forge login
Log in to your Atlassian account
Press Ctrl+C to cancel.

? Enter your email: gianpaolo.macario@solarma.it

Next, enter your Atlassian API token. If you don't have a token, visit this URL to create one:
https://id.atlassian.com/manage/api-tokens

? Enter your Atlassian API token: [hidden]

✔ Logged in as Gianpaolo Macario (SOLARMA).

Now try forge create to start a new app.
gmacario@hw2228:~/github/aquariophilie/axolotl$
```

Register the app

```text
gmacario@hw2228:~/github/aquariophilie/axolotl$ forge register
Registering the app to you.
Press Ctrl+C to cancel.


Name your app. The app name can include dashes, spaces, and underscores.

? Enter a name for your app: AXOLOTL

✔ Registering app...

ℹ Registering app
ℹ Creating environments

✔ Registered AXOLOTL

Your app is ready to work on, deploy, and install. We created 3 environments you can deploy to: development, staging, production.

Use forge deploy to deploy your app to an environment.
gmacario@hw2228:~/github/aquariophilie/axolotl$
```

Install dependencies

```text
gmacario@hw2228:~/github/aquariophilie/axolotl$ npm install
npm WARN old lockfile 
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile 
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile 
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies

added 516 packages, and audited 517 packages in 29s

6 packages are looking for funding
  run `npm fund` for details

12 vulnerabilities (2 moderate, 9 high, 1 critical)

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
gmacario@hw2228:~/github/aquariophilie/axolotl$
```

(2022-05-02 10:55 CEST)

Deploy the app

```text
gmacario@hw2228:~/github/aquariophilie/axolotl$ forge deploy
Deploying your app to the development environment.
Press Ctrl+C to cancel.

Running forge lint...
1 issue found. Run forge lint to review the warnings.

✔ Deploying your app to development...

ℹ Packaging app files
ℹ Uploading app
ℹ Validating manifest
ℹ Snapshotting functions
ℹ Deploying to environment

✔ Deployed

Deployed your app to the development environment.
gmacario@hw2228:~/github/aquariophilie/axolotl$
```

And finally install it on your site

```text
gmacario@hw2228:~/github/aquariophilie/axolotl$ forge install
Select the product your app uses.

? Select a product: Confluence

Enter your site. For example, your-domain.atlassian.net

? Enter the site URL: https://solarma.atlassian.net/

Installing your app onto an Atlassian site.
Press Ctrl+C to cancel.

Your app will be installed with the following scopes:
- read:me
- read:confluence-content.summary

? Do you want to continue? Yes

✔ Install complete!

Your app in the development environment is now installed in Confluence on solarma.atlassian.net
gmacario@hw2228:~/github/aquariophilie/axolotl$
```

Verified at <https://solarma.atlassian.net/wiki/plugins/servlet/upm?source=side_nav_manage_addons>
that the User-installed app "AXOLOTL - DEVELOPMENT" is available.
